### ISSUE TITLE
Fazer orçamento oficial com a Empresa Júnior de Elétrica da UFMG 

### ISSUE THREAD

**Issue by AmandaFuso** [rvnovaes/gestaolegal#24]
Pegar o contato de um responsável com o Leo

**Comment by Sarahfrancos** [comment]
Vou entrar em contato e mandar a resposta deles por aqui.

**Comment by AmandaFuso** [comment]
Na última reunião do dia 31/10, ficou decidido que faríamos um documento de Definição dos Requisitos do Software que será elaborado, tanto para a seleção das Empresas juniores, quanto para os programadores avulsos. 
Logo, a seleção será unificada.
