### ISSUE TITLE
Fazer orçamento oficial com Programadores avulsos 

### ISSUE THREAD

**Issue by AmandaFuso** [rvnovaes/gestaolegal#25]

**Comment by Alex19-tech** [comment]
Fiz um orçamento com o Lucas Pellegrineli, um amigo meu do ensino médio que hoje faz Ciência da Computação na UFMG e faz alguns serviços de free-lancer. 
Descrevi para ele os requisitos do software do plantão apenas, o que inclui cadastramento completo dos assistidos, questionário socioeconomico, geração de relatórios e anexação de documentos do assistido. Falei com ele que queriamos um software online e que já temos um servidor de banco de dados na faculdade.
Ele me disse que, pelos requisitos falados, ele cobraria cerca de R$1200,00, e entregaria esse software em cerca de 1 mês e meio. 
OBS: para conferirmos preços, percebi que precisamos fechar a lista de requisitos.

**Comment by Alex19-tech** [comment]
### Orçamento e questão

Fiz um segundo orçamento, dessa vez com o Guilherme. Guilherme é amigo meu de ensino médio que hoje faz Ciência da Computação em Viçosa. Ele estagia na empresa júnior de informática da UFV basicamente desde que entrou no curso, já foi diretor de vendas e diretor-geral da empresa junior (AKA No-Bugs). Eu pedi ele para elaborar um orçamento para mim de quanto custaria para a No-bugs fazer o software que queremos. O valor que ele calculou por alto usando as variáveis da empresa junior foi de R$6..112,02, com previsão de 4 a 5 meses de trabalho. Perguntei a ele se o programa fruto da No-bugs poderia se tornar de código-aberto e ele me disse que sim, bastava apenas uma alteração contratual. Além disso, ele disse que o setor comercial da No bugs entraria em contato me enviando o orçamento definitivo.

**O que faz haver uma discrepância tão grande entre o primeiro orçamento e o segundo?**

Essa foi a dúvida a qual me questionei. Minha conclusão foi a de que não temos os requisitos para nosso software bem definidos. Assim, enquanto um programador imagina uma determinada tela de cadastro, outro imagina ela de outra forma, contendo outros dados e outros requerimentos.
Isso ficou mais claro para mim quando perguntei o Guilherme a seguinte questão: 

> "O preço fechado é esse, mas o que faz nosso software diferente de um software no mesmo estilo que faça ele ficar mais caro?" 

Guilherme me disse que a funcionalidade de geração de relatórios dentro do próprio programa aumentava em cerca de R$1000 o preço final, por ser descrito como um "requisito complexo". Por outro, ele me disse que se o programa na verdade gerasse uma planilha que pudesse por fora ser utilizada para um relatório, isso diminuiria os custos do requisito.
Quando ele me respondeu isso, eu me questionei se (i) a geração de relatórios dentro do software é realmente uma necessidade e (ii) poderíamos fazê-la da forma que ele sugeriu para diminuir o preço final?

**Quais minhas conclusões?**
Precisamos de um documento, uma apresentação, chamada de "Convite de Desenvolvimento". Nela haverá todos os requisitos essenciais e os requisitos opcionais para o software que pretendemos desenvolver. Isso inclui, por exemplo:
- Tela de cadastro de acolhido contendo nome, telefone, endereço, cep
- Tela de continuação de cadastro de acolhido contendo descrição jurídica dos fatos e encaminhamento
- Tela de preenchimento de questionário socioeconomico contendo dados de renda, lucro, bens e imóveis
- OPCIONAL: Tela para geração de relatórios no próprio programa com seleção de variáveis como bairro, idade, escolaridade, etc.

**Essa Carta resolveria dois problemas:**
1. Como várias pessoas vão correr atrás de desenvolvedores e Empresas Juniores, isso certifica que todos os membros do Gestão Legal partiram das mesmas variáveis para chegar a um preço de custo, o que garante que o resultado final dos vários orçamentos seja comparável entre eles.
2. Isso nos ajuda a estabelecer quais são as requisitos que são prioridades do software que pretendemos desenvolver e quais não são e podem ser fruto do futuro hackaton.

**Comment by AmandaFuso** [comment]
https://www.canva.com/design/DADptPxljQs/share/preview?token=6kCSbu9ZKPGHBcUva4xrhQ&role=EDITOR&utm_content=DADptPxljQs&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton 

Convite para editar flyer de divulgação da seleção de programador de Software

**Comment by AmandaFuso** [comment]
https://www.canva.com/design/DADptPxljQs/share/preview?token=6kCSbu9ZKPGHBcUva4xrhQ&role=EDITOR&utm_content=DADptPxljQs&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton 

Convite para editar, flyer de seleção de Programador de Software livre

**Comment by AmandaFuso** [comment]
Ficou decidido na última reunião que será elaborado essa Proposta de Requisitos, que servirá como base para a proposta de Empresas juniores, quanto para programadores avulsos
